# Generated by Django 3.2 on 2023-04-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzsDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_azs', models.CharField(max_length=50, verbose_name='Номер АЗС')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='Долгота')),
                ('DT', models.CharField(blank=True, max_length=20, null=True, verbose_name='ДТ')),
                ('DT_Taneko', models.CharField(blank=True, max_length=20, null=True, verbose_name='ДТ_танеко')),
            ],
        ),
    ]
