# Generated by Django 3.2 on 2023-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azsdb',
            name='DT_arctic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ДТ_арктика'),
        ),
        migrations.AddField(
            model_name='azsdb',
            name='DT_winter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ДТ_зимнее'),
        ),
    ]
